global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自体のメトリクス
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hono Logger サービス
  - job_name: 'hono-logger'
    static_configs:
      - targets: ['hono-logger:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis メトリクス
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Consul メトリクス
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']

  # Node Exporter（システムメトリクス）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

